name: lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
        config_file: ".markdownlidevelopnt.yaml"

  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: dockerlint
      uses: brpaz/hadolint-action@v1.1.0
      with:
        dockerfile: Dockerfile
